name: open_document
description: A new flutter plugin project.
version: 1.0.0
homepage: https://github.com/fabio21/open_document.git
repository: https://github.com/fabio21/open_document.git

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.3.1
  flutter_slidable: ^2.0.0
  path_provider_windows: ^2.1.2
  share_plus: ^4.0.10+1
  intl: ^0.17.0
  platform: ^3.1.0
  url_launcher: ^6.1.5
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  dartdoc: ^6.0.1  

flutter:
  plugin:
    platforms:
      android:
        package: com.example.open_document
        pluginClass: OpenDocumentPlugin
      ios:
        pluginClass: OpenDocumentPlugin
      macos:
        pluginClass: OpenDocumentPlugin


































